version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ~/uploadData:/app/uploadData
    environment:
      - PORT=${PORT}
      - STATIC_PATH=${STATIC_PATH}
