version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${LOCAL_PATH}:${STATIC_PATH}
    environment:
      - PORT=${PORT}
      - STATIC_PATH=${STATIC_PATH}
